node_js:
  - "0.12"

script: node_modules/karma/bin/karma start karma.conf.js --single-run

before_script:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'npm install'